package ru.sbrf.ckr.sberboard.kafkapersistservice.entity;

import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@Entity
@Table(name = "cx_txb_evt", schema = "RAW_DATA_nrt")
public class CxTxbEvt {
    private String zp;
    private String x_txb_source;
    private String x_txb_prod;
    private String x_txb_org_type;
    private String x_txb_kic_subtype;
    private String x_txb_cont_numb;
    private String x_txb_cont_fio;
    private String x_txb_code_id;
    private String x_txb_code;
    private String x_txb_act;
    private String x_tlt_vsp;
    private LocalDateTime x_tlt_to_vko_dt;
    private String x_tlt_tb;
    private LocalDateTime x_tlt_reserv_dt;
    private String x_tlt_reason;
    private String x_tlt_osp;
    private String x_tlt_org_name;
    private String x_tlt_msc2_res;
    private LocalDateTime x_tlt_msc2_dt;
    private String x_tlt_msc1_res;
    private String x_tlt_inn;
    private String x_tlt_agr_num;
    private LocalDateTime x_tlt_agr_date;
    private String x_sign_type;
    private String x_sg_type;
    private String x_sg_templ_type;
    private String x_sg_number;
    private String x_sg_mid_name;
    private String x_sg_mid_cl_name;
    private String x_sg_lst_name;
    private String x_sg_lst_cl_name;
    private String x_sg_job_title;
    private String x_sg_job_cl_title;
    private String x_sg_full_name;
    private String x_sg_fst_name;
    private String x_sg_fst_cl_name;
    private String x_sg_doc;
    private LocalDateTime x_sg_date;
    private String x_sg_cl_number;
    private String x_sg_cl_full_name;
    private String x_sg_cl_doc;
    private LocalDateTime x_sg_cl_date;
    private BigDecimal x_sbrf_wk_h_dur_act;
    private BigDecimal x_sbrf_wk_h_dur;
    private String x_rpa_flag;
    private String x_rpa_comment;
    private String x_req_sign;
    private String x_req_scan;
    private String x_req_doc;
    private String x_operation_uid;
    private String x_new_prod_flg;
    private String x_kic_oc_city;
    private String x_kic_divn_id;
    private String x_indicator;
    private String x_ic_spec;
    private String x_ic_reason;
    private String x_ic_judgement;
    private String x_ic_comment;
    private String x_ex_created_by;
    private String x_expertice_id;
    private String x_doc;
    private String x_delegated_flg;
    private String x_condition;
    private String x_client_it;
    private String x_client_count;
    private LocalDateTime x_assign_dt;
    private String x_act_source;
    private String x_act_code;
    private BigDecimal work_remain_min;
    private LocalDateTime wait_change_dt;
    private String txb_wait;
    private LocalDateTime todo_plan_start_dt;
    private LocalDateTime todo_plan_end_dt;
    private String todo_cd;
    private LocalDateTime todo_after_dt;
    private LocalDateTime todo_actl_start_dt;
    private LocalDateTime todo_actl_end_dt;
    private String te;
    private String target_per_id;
    private String target_ou_id;
    private String st_l;
    private LocalDateTime stage2_start;
    private LocalDateTime stage1_start;
    private String sent_bbmo_flg;
    private BigDecimal sbrf_duration_planned_min;
    private String sbrf_cg_id;
    private String sbbol_login;
    private String sbbol_flg;
    @Id
    private String row_id;
    private String result;
    private String reg_address;
    private String pr_sr_id;
    private String priority_cd;
    private String prev_act_id;
    private String pprb_agr_id;
    private BigDecimal pct_complete;
    private String par_act_id;
    private String owner_postn_id;
    private String owner_per_id;
    private String owner_login;
    private String opty_id;
    private String name;
    private String mvd;
    private String msh_release_id;
    private String msh_prod_id;
    private BigDecimal modification_num;
    private String last_upd_by;
    private LocalDateTime last_upd;
    private String km_visibility;
    private String kic_flg;
    private String frames_flg;
    private String evt_stat_cd;
    private String ecm_tdkkb_id;
    private BigDecimal duration_hrs;
    private String done_flg;
    private LocalDateTime delay_to_dt;
    private String decision;
    private String db_last_upd_src;
    private LocalDateTime db_last_upd;
    private String created_by;
    private LocalDateTime created;
    private String conflict_id;
    private String collect_flg;
    private String cash_agreem_id;
    private String bi;
    private String auto_close_inc_flg;
    private String auto_close_flg;
    private LocalDateTime appt_start_dt;
    private String appt_rept_type;
    private String appt_rept_repl_cd;
    private String appt_rept_flg;
    private LocalDateTime appt_rept_end_dt;
    private BigDecimal appt_end_tm;
    private LocalDateTime appt_end_dt;
    private BigDecimal appt_duration_min;
    private BigDecimal appt_alarm_tm_min;
    private String alarm_flag;
    private String agreem_num;
    private LocalDateTime ctl_validfrom;
    private String ctl_action;
    private Long ctl_loading;
    private BigDecimal ctl_csn;

}
