package ru.sbrf.ckr.sberboard.kafkapersistservice.entity;

import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@Entity
@Table(name = "S_SRV_REQ", schema = "RAW_DATA_NRT")
public class SSrvReq extends MessageObject {
    @Column(name = "PRI_LST_ID")
    private String priLstId;
    @Column(name = "SYMPTOM_DSCVRY_TS")
    private LocalDateTime symptomDscvryTs;
    @Column(name = "OWNER_OU_ID")
    private String ownerOuId;
    @Column(name = "ROW_STATUS")
    private String rowStatus;
    @Column(name = "INTEGRATION_ID")
    private String integrationId;
    @Column(name = "CEM_PLAN_START_DT")
    private LocalDateTime cemPlanStartDt;
    @Column(name = "ACCNT_TXN_ID")
    private String accntTxnId;
    @Column(name = "X_CALL_ID")
    private String xCallId;
    @Column(name = "X_SUPRESS_PGONE_NUMBER")
    private String xSupressPgoneNumber;
    @Column(name = "ASGN_SYS_FLG")
    private String asgnSysFlg;
    @Column(name = "ROOT_CAUSE_CD")
    private String rootCauseCd;
    @Column(name = "ALT_CON_PH_NUM")
    private String altConPhNum;
    @Column(name = "SR_CATEGORY_CD")
    private String srCategoryCd;
    @Column(name = "PUBLISH_CD")
    private String publishCd;
    @Column(name = "SR_DATABASE")
    private String srDatabase;
    @Column(name = "EXP_CLOSE_DT")
    private LocalDateTime expCloseDt;
    @Column(name = "SRV_REGN_ID")
    private String srvRegnId;
    @Column(name = "PR_SURVEY_ID")
    private String prSurveyId;
    @Column(name = "LAST_UPD_BY")
    private String lastUpdBy;
    @Column(name = "AGREE_ID")
    private String agreeId;
    @Column(name = "CUST_CON_PH_NUM")
    private String custConPhNum;
    @Column(name = "SM_DATA_ID")
    private String smDataId;
    @Column(name = "X_AREA")
    private String xArea;
    @Column(name = "ACT_ID")
    private String actId;
    @Column(name = "SRV_FEE_FLG")
    private String srvFeeFlg;
    @Column(name = "SR_CREATED_DT")
    private LocalDateTime srCreatedDt;
    @Column(name = "NEW_SEC_ANSWR")
    private String newSecAnswr;
    @Column(name = "JOB_TOT_ORDER_NUM")
    private BigDecimal jobTotOrderNum;
    @Column(name = "CST_CON_ID")
    private String cstConId;
    @Column(name = "BASED_ON_SR_ID")
    private String basedOnSrId;
    @Column(name = "X_NUM_OUT_LETTER")
    private String xNumOutLetter;
    @Column(name = "INIT_SEV_CD")
    private String initSevCd;
    @Column(name = "SMART_ISSUE_ID")
    private String smartIssueId;
    @Column(name = "PR_SYMPTOM_CD")
    private String prSymptomCd;
    @Column(name = "SR_CST_NUM")
    private String srCstNum;
    @Column(name = "BILLACCT_ID")
    private String billacctId;
    @Column(name = "CEM_DUE_DT")
    private LocalDateTime cemDueDt;
    @Column(name = "INCIDENT_ID")
    private String incidentId;
    @Column(name = "NEW_SEC_QUEST_CD")
    private String newSecQuestCd;
    @Column(name = "DOC_REQD_FLG")
    private String docReqdFlg;
    @Column(name = "X_GOSB_OSB_VSP_ID")
    private String xGosbOsbVspId;
    @Column(name = "TO_CONTAINER_ID")
    private String toContainerId;
    @Column(name = "TYPE_CD")
    private String typeCd;
    @Column(name = "SRV_FEE")
    private BigDecimal srvFee;
    @Column(name = "POST_MORTEM_RVW_BY")
    private String postMortemRvwBy;
    @Column(name = "X_INTEGRATION_ID")
    private String xInteractionId;
    @Column(name = "PM_ACTION_ID")
    private String pmActionId;
    @Column(name = "DISEASE_ID")
    private String diseaseId;
    @Column(name = "SOURCE_TYP_CD")
    private String sourceTypCd;
    @Column(name = "X_SERVICE_VSP_ID")
    private String xServiceVspId;
    @Column(name = "X_DIV_PIN_ID")
    private String xDivPinId;
    @Column(name = "INIT_CUST_SEV_CD")
    private String initCustSevCd;
    @Column(name = "SR_SEV_CD")
    private String srSevCd;
    @Column(name = "ENTLMNT_MTRC_ID")
    private String entlmntMtrcId;
    @Column(name = "ORG_PRDINT_ID")
    private String orgPrdintId;
    @Column(name = "PROD_UND_WRNTY_FLG")
    private String prodUndWrntyFlg;
    @Column(name = "CREATED_BY")
    private String createdBy;
    @Column(name = "ACT_CLOSE_DT")
    private LocalDateTime actCloseDt;
    @Column(name = "ASGN_USR_EXCLD_FLG")
    private String asgnUsrExcldFlg;
    @Column(name = "OU_ADDR_ID")
    private String ouAddrId;
    @Column(name = "INS_PRODUCT")
    private String insProduct;
    @Column(name = "ODOMTR_RDNG")
    private BigDecimal odomtrRdng;
    @Column(name = "CON_PRDINT_ID")
    private String conPrdintId;
    @Column(name = "BEST_CALL_TM")
    private String bestCallTm;
    @Column(name = "SR_AREA")
    private String srArea;
    @Column(name = "PER_ADDR_ID")
    private String perAddrId;
    @Column(name = "BU_ID")
    private String buId;
    @Column(name = "CONFLICT_ID")
    private String conflictId;
    @Column(name = "X_VSP_ID")
    private String xVspId;
    @Column(name = "LAST_UPD")
    private LocalDateTime lastUpd;
    @Column(name = "JOB_REF_NUM")
    private String jobRefNum;
    @Column(name = "ALERT_USER_FLG")
    private String alertUserFlg;
    @Column(name = "CEM_TIME_UOM_CD")
    private String cemTimeUomCd;
    @Column(name = "COMM_METHOD_CD")
    private String commMethodCd;
    @Column(name = "RECOMMENDATION_CD")
    private String recommendationCd;
    @Column(name = "SR_NUM")
    private String srNum;
    @Column(name = "PR_MED_DGNSIS_ID")
    private String prMedDgnsisId;
    @Column(name = "SR_OS")
    private String srOs;
    @Column(name = "SRV_FEE_REASON_CD")
    private String srvFeeReasonCd;
    @Column(name = "SRV_PROV_OU_ID")
    private String srvProvOuId;
    @Column(name = "PROD_LN_FEE_ID")
    private String prodLnFeeId;
    @Column(name = "ODOMTR_UOM_CD")
    private String odomtrUomCd;
    @Column(name = "SR_REPRODUCE")
    private String srReproduce;
    @Column(name = "SRV_FEE_CURCY_CD")
    private String srvFeeCurcyCd;
    @Column(name = "INS_REC_TYPE")
    private String insRecType;
    @Column(name = "ACT_OPEN_DT")
    private LocalDateTime actOpenDt;
    @Column(name = "CUST_CON_EMAIL")
    private String custConEmail;
    @Column(name = "PR_PROFILE_ID")
    private String prProfileId;
    @Column(name = "X_PHONE_NUMBER")
    private String xPhoneNumber;
    @Column(name = "X_ALERT_ID")
    private String xAlertId;
    @Column(name = "SR_TYPE_CD")
    private String srTypeCd;
    @Column(name = "ASGN_DT")
    private LocalDateTime asgnDt;
    @Column(name = "COMP_UND_WRNTY_FLG")
    private String compUndWrntyFlg;
    @Column(name = "RESOLUTION_CD")
    private String resolutionCd;
    @Column(name = "SP_PRDINT_ID")
    private String spPrdintId;
    @Column(name = "REASON_CD")
    private String reasonCd;
    @Column(name = "CST_SATISFY_CD")
    private String cstSatisfyCd;
    @Column(name = "X_SR_STAGE")
    private String xSrStage;
    @Column(name = "FRM_CONTAINER_ID")
    private String frmContainerId;
    @Column(name = "COMM_DESC")
    private String commDesc;
    @Column(name = "TO_TELLER_ID")
    private String toTellerId;
    @Column(name = "OWNER_EMP_ID")
    private String ownerEmpId;
    @Column(name = "PR_MED_PROC_ID")
    private String prMedProcId;
    @Column(name = "SR_STAT_ID")
    private String srStatId;
    @Column(name = "CASE_ID")
    private String caseId;
    @Column(name = "SUPRV_RVW_FLG")
    private String suprvRvwFlg;
    @Column(name = "ASGN_DNRM_FLG")
    private String asgnDnrmFlg;
    @Column(name = "SR_TITLE")
    private String srTitle;
    @Column(name = "PROJ_ID")
    private String projId;
    @Column(name = "PR_CON_ORG_ID")
    private String prConOrgId;
    @Column(name = "ORG_GROUP_ID")
    private String orgGroupId;
    @Column(name = "DESC_TEXT")
    private String descText;
    @Column(name = "SR_SUB_STAT_ID")
    private String srSubStatId;
    @Column(name = "RTNG_CD")
    private String rtngCd;
    @Column(name = "SR_STAT_DT")
    private LocalDateTime srStatDt;
    @Column(name = "BRANCH_ID")
    private String branchId;
    @Column(name = "TEMP_PH_NUM")
    private String tempPhNum;
    @Column(name = "COMM_NEED_FLG")
    private String commNeedFlg;
    @Column(name = "ACTL_RESOLVED_TS")
    private LocalDateTime actlResolvedTs;
    @Column(name = "SR_PRIO_CD")
    private String srPrioCd;
    @Column(name = "X_NUM_REG_LETTER")
    private String xNumRegLetter;
    @Column(name = "X_DATE_OUT_LETTER")
    private LocalDateTime xDateOutLetter;
    @Column(name = "ACCNT_CON_ID")
    private String accntConId;
    @Column(name = "PR_PAR_SR_ID")
    private String prParSrId;
    @Column(name = "X_ORIGIN_VSP_ID")
    private String xOriginVspId;
    @Column(name = "INSCLM_ID")
    private String insclmId;
    @Id
    @Column(name = "ROW_ID")
    private String rowId;
    @Column(name = "X_AUTO_CLOSED")
    private String xAutoClosed;
    @Column(name = "RATE_LST_ID")
    private String rateLstId;
    @Column(name = "BILLABLE_FLG")
    private String billableFlg;
    @Column(name = "SP_ASSET_ID")
    private String spAssetId;
    @Column(name = "SR_URGENCY_CD")
    private String srUrgencyCd;
    @Column(name = "FEE_CENTER_ID")
    private String feeCenterId;
    @Column(name = "ALT_CON_EMAIL")
    private String altConEmail;
    @Column(name = "CREATED")
    private LocalDateTime created;
    @Column(name = "ALT_CONTACT_NAME")
    private String altContactName;
    @Column(name = "OVERRIDE_ID")
    private String overrideId;
    @Column(name = "PR_PRD_CMPLNT_ID")
    private String prPrdCmplntId;
    @Column(name = "SR_CREATED_BY")
    private String srCreatedBy;
    @Column(name = "SR_CAT_TYPE_CD")
    private String srCatTypeCd;
    @Column(name = "SR_IMPACT_CD")
    private String srImpactCd;
    @Column(name = "CEM_PLAN_END_DT")
    private LocalDateTime cemPlanEndDt;
    @Column(name = "UND_MFG_WRNTY_FLG")
    private String undMfgWrntyFlg;
    @Column(name = "ACTL_RESP_TS")
    private LocalDateTime actlRespTs;
    @Column(name = "TEMPLATE_FLG")
    private String templateFlg;
    @Column(name = "OPTY_ID")
    private String optyId;
    @Column(name = "X_SR_REG_TIME_UTC")
    private LocalDateTime xSrRegTimeUtc;
    @Column(name = "SR_SUBTYPE_CD")
    private String srSubtypeCd;
    @Column(name = "ASSET_REG_ID")
    private String assetRegId;
    @Column(name = "JOB_TYPE_CD")
    private String jobTypeCd;
    @Column(name = "SR_SUB_AREA")
    private String srSubArea;
    @Column(name = "X_EMP_ID")
    private String xEmpId;
    @Column(name = "SR_ESCL_TS")
    private LocalDateTime srEsclTs;
    @Column(name = "DB_LAST_UPD_SRC")
    private String dbLastUpdSrc;
    @Column(name = "DB_LAST_UPD")
    private LocalDateTime dbLastUpd;
    @Column(name = "CEM_TOTAL_TIME")
    private BigDecimal cemTotalTime;
    @Column(name = "NOTIFY_DT")
    private LocalDateTime notifyDt;
    @Column(name = "WRNTY_LAST_UPD_DT")
    private LocalDateTime wrntyLastUpdDt;
    @Column(name = "SR_PROD_VERSION")
    private String srProdVersion;
    @Column(name = "PR_CON_ID")
    private String prConId;
    @Column(name = "SRV_FEE_DT")
    private LocalDateTime srvFeeDt;
    @Column(name = "APPT_REQ_FLG")
    private String apptReqFlg;
    @Column(name = "DOCK_FLG")
    private String dockFlg;
    @Column(name = "INIT_COMMIT_TS")
    private LocalDateTime initCommitTs;
    @Column(name = "X_APPR_PKK_COMM")
    private String xApprPkkComm;
    @Column(name = "ASGN_MANL_FLG")
    private String asgnManlFlg;
    @Column(name = "COMM_ID")
    private String commId;
    @Column(name = "ASSET_ID")
    private String assetId;
    @Column(name = "REOPENED_TS")
    private LocalDateTime reopenedTs;
    @Column(name = "RTNG_DLR_ID")
    private String rtngDlrId;
    @Column(name = "DOC_RECV_FLG")
    private String docRecvFlg;
    @Column(name = "APPROVED_FLG")
    private String approvedFlg;
    @Column(name = "POST_MORTEM_RVW_DT")
    private LocalDateTime postMortemRvwDt;
    @Column(name = "CST_OU_ID")
    private String cstOuId;
    @Column(name = "PRDINT_ID")
    private String prdintId;
    @Column(name = "LOT_NUM")
    private String lotNum;
    @Column(name = "MODIFICATION_NUM")
    private BigDecimal modificationNum;
    @Column(name = "AGENT_COMMENTS")
    private String agentComments;
    @Column(name = "TT_TYPE_CD")
    private String ttTypeCd;
    @Column(name = "CALLBACK_REQ_FLG")
    private String callbackReqFlg;
    @Column(name = "INS_REQUEST_BY")
    private String insRequestBy;
    @Column(name = "X_APPR_PKK")
    private String xApprPkk;
    @Column(name = "TARGET_CON_ID")
    private String targetConId;
    @Column(name = "PAR_SR_ID")
    private String parSrId;
    @Column(name = "INCR_PACK_RUN_ID")
    private Long incrPackRunId;
    @Column(name = "CTL_ACTION")
    private String ctlAction;
    @Column(name = "CTL_CSN")
    private BigDecimal ctlCsn;
    @Column(name = "CTL_LOADING")
    private Long ctlLoading;
    @Column(name = "CTL_SEQNO")
    private Long ctlSeqno;
    @Column(name = "CTL_VALIDFROM")
    private LocalDateTime ctlValidfrom;
}
